# Generated by Django 4.1 on 2023-03-18 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('correoPersonal', models.EmailField(blank=True, max_length=254)),
                ('tipouser', models.CharField(choices=[('E_V', 'Encargado de ventas'), ('D_R', 'Director general'), ('E_A', 'Encargado de Acopio'), ('I_C', 'Ingeniero de campo'), ('E_B', 'Encargado de bitacora'), ('G_C', 'Gerente de cuadrillas'), ('E_P', 'Encargado de produccion'), ('ADM', 'Administrador')], default='TU', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
    ]
