# Generated by Django 4.1 on 2023-03-18 02:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agronomunnity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employes',
            new_name='user',
        ),
    ]
