# Generated by Django 4.1 on 2023-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0002_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='temaIncidencia',
            field=models.CharField(choices=[('B_T', 'Bitacoras'), ('C_M', 'Camiones'), ('C_A', 'Calidad'), ('C_L', 'Clientes'), ('C_D', 'Cuadrillas'), ('D_C', 'Documentos'), ('E_N', 'Encargados'), ('G_R', 'Gerentes'), ('H_R', 'Huertas'), ('G_F', 'Jefes'), ('O_C', 'Ordenes de corte'), ('P_D', 'Pedidos'), ('P_T', 'Productores'), ('T_B', 'Trabajadores'), ('T_P', 'Transportes'), ('V_J', 'Viajes')], default='Bitacoras', max_length=3),
        ),
    ]
