# Generated by Django 4.1 on 2023-03-27 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agronomunnity', '0002_rename_employes_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.CharField(blank=True, max_length=20)),
                ('estatus', models.CharField(choices=[('C_A', 'Activo'), ('C_I', 'Inactivo'), ('C_M', 'Mantenimiento')], default='Activo', max_length=3)),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camiones',
                'db_table': 'camion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Cuadrilla',
                'verbose_name_plural': 'Cuadrillas',
                'db_table': 'cuadrilla',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Huerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=30)),
                ('estatus', models.CharField(choices=[('H_A', 'Activo'), ('H_I', 'Inactivo')], default='Activo', max_length=3)),
                ('fruta', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Huerta',
                'verbose_name_plural': 'MHuertas',
                'db_table': 'huerta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MiembroCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('apellidoP', models.CharField(blank=True, max_length=30)),
                ('apellidoM', models.CharField(blank=True, max_length=30)),
                ('idCuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.cuadrilla')),
            ],
            options={
                'verbose_name': 'MiembroC',
                'verbose_name_plural': 'MiembrosC',
                'db_table': 'miembroc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, max_length=10)),
                ('tipoFruta', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateField()),
                ('calidadFruta', models.CharField(blank=True, max_length=20)),
                ('estatus', models.CharField(choices=[('P_C', 'Por cumplir'), ('Y_T', 'Terminado')], default='Activo', max_length=3)),
            ],
            options={
                'verbose_name': 'OrdenCorte',
                'verbose_name_plural': 'OrdenesCorte',
                'db_table': 'ordenCorte',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(blank=True, max_length=20)),
                ('apellidoPCliente', models.CharField(blank=True, max_length=20)),
                ('apellidoMCliente', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.FloatField(blank=True, max_length=10)),
                ('tipoFruta', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateField()),
                ('calidadFruta', models.CharField(blank=True, max_length=20)),
                ('estatus', models.CharField(choices=[('P_C', 'Por cumplir'), ('Y_T', 'Terminado')], default='Activo', max_length=3)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('apellidoP', models.CharField(blank=True, max_length=30)),
                ('apellidoM', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
                'db_table': 'productor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(upload_to='Reportes/Corte')),
                ('idCuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.cuadrilla')),
            ],
            options={
                'verbose_name': 'ReporteCorte',
                'verbose_name_plural': 'ReportesCortes',
                'db_table': 'reportecorte',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('correoPersonal', models.EmailField(blank=True, max_length=254)),
                ('rol', models.CharField(choices=[('E_B', 'Encargado de bitacora'), ('E_V', 'Encargado de ventas'), ('E_P', 'Encargado de produccion'), ('D_G', 'Director General'), ('I_C', 'Ingeniero de campo'), ('G_C', 'Gerente de cuadrilla'), ('C_C', 'Capataz de cuadrilla'), ('C_T', 'Chofer de transporte')], default='', max_length=3)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'trabajador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horaSalida', models.TimeField(blank=True, max_length=20)),
                ('horaLlegada', models.TimeField(blank=True, max_length=20)),
                ('estatus', models.CharField(choices=[('P_R', 'Por realizar'), ('V_R', 'Realizado')], default='Activo', max_length=3)),
                ('idCamion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.camion')),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.ordencorte')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'viaje',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='ordencorte',
            name='idViaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.viaje'),
        ),
        migrations.AddField(
            model_name='huerta',
            name='idProductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.productor'),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='idCapatazCuadrilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capataz', to='Agronomunnity.trabajador'),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='idGerenteCuadrilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='Agronomunnity.trabajador'),
        ),
        migrations.AddField(
            model_name='camion',
            name='idChofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.trabajador'),
        ),
    ]
