# Generated by Django 4.1 on 2023-04-30 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0003_incidencia_temaincidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencorte',
            name='calidadFruta',
        ),
        migrations.RemoveField(
            model_name='ordencorte',
            name='cantidadFruta',
        ),
        migrations.RemoveField(
            model_name='ordencorte',
            name='estatusOrden',
        ),
        migrations.RemoveField(
            model_name='ordencorte',
            name='idHuerta',
        ),
        migrations.RemoveField(
            model_name='viajecorte',
            name='estatusViaje',
        ),
        migrations.AddField(
            model_name='ordencorte',
            name='idPedido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.pedido'),
        ),
        migrations.AddField(
            model_name='viajecorte',
            name='idHuerta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.huerta'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estatusIncidencia',
            field=models.CharField(choices=[('I_P', 'Pendiente'), ('I_R', 'Resuelta')], default='I_P', max_length=3),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='temaIncidencia',
            field=models.CharField(choices=[('B_T', 'Bitacoras'), ('C_M', 'Camiones'), ('C_A', 'Calidad'), ('C_L', 'Clientes'), ('C_D', 'Cuadrillas'), ('D_C', 'Documentos'), ('E_N', 'Encargados'), ('G_R', 'Gerentes'), ('H_R', 'Huertas'), ('G_F', 'Jefes'), ('O_C', 'Ordenes de corte'), ('P_D', 'Pedidos'), ('P_T', 'Productores'), ('T_B', 'Trabajadores'), ('T_P', 'Transportes'), ('V_J', 'Viajes')], default='B_T', max_length=3),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estatusPedido',
            field=models.CharField(choices=[('P_I', 'Iniciado'), ('P_O', 'Ordenado'), ('P_P', 'En viaje'), ('P_C', 'Completado')], default='Pendiente', max_length=3),
        ),
        migrations.AlterModelTable(
            name='ordencorte',
            table='ordencorte',
        ),
    ]
