# Generated by Django 4.1 on 2023-03-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0003_camion_cuadrilla_huerta_miembrocuadrilla_ordencorte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='rol',
            field=models.CharField(choices=[('E_V', 'Encargado de ventas'), ('E_B', 'Encargado de bitacora'), ('E_P', 'Encargado de produccion'), ('E_T', 'Encargado de transporte'), ('D_G', 'Director General'), ('I_C', 'Ingeniero de campo'), ('G_C', 'Gerente de cuadrilla'), ('C_C', 'Capataz de cuadrilla'), ('C_T', 'Chofer de transporte')], default='', max_length=3),
        ),
    ]
