# Generated by Django 4.1 on 2023-05-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0004_remove_ordencorte_calidadfruta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estatusPedido',
            field=models.CharField(choices=[('P_I', 'Iniciado'), ('P_O', 'Ordenado'), ('P_V', 'En viaje'), ('P_C', 'Completado')], default='Pendiente', max_length=3),
        ),
        migrations.AlterField(
            model_name='viajecorte',
            name='horaLlegada',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
    ]
