# Generated by Django 4.1 on 2023-05-17 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0005_alter_pedido_estatuspedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibre',
            name='descripcionCalibre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacionPedido',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mercadoPedido',
            field=models.CharField(choices=[('M_N', 'Nacional'), ('M_E', 'Exportación'), ('M_O', 'Otros destinos')], default='Nacional', max_length=3),
        ),
        migrations.CreateModel(
            name='OrdenCalibreCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadCC', models.IntegerField(blank=True)),
                ('idCalibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.calibre')),
                ('idCalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.calidad')),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.ordencorte')),
            ],
            options={
                'verbose_name': 'OrdenCalibreCalidad',
                'verbose_name_plural': 'OrdenesCalibreCalidad',
                'db_table': 'ordencalibrecalidad',
                'ordering': ['id'],
            },
        ),
    ]
