# Generated by Django 4.1 on 2023-05-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0006_calibre_descripcioncalibre_pedido_observacionpedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencorte',
            name='tipoFruta',
        ),
        migrations.AddField(
            model_name='ordencorte',
            name='frutaHuerta',
            field=models.CharField(choices=[('', '(Seleccione)'), ('AVN', 'Aventajado'), ('FLC', 'Flor loca')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='ordencorte',
            name='tipoHuerta',
            field=models.CharField(choices=[('', '(Seleccione)'), ('HSS', 'Aguacate Hass'), ('MDZ', 'Aguacate Mendez'), ('CLL', 'Aguacate Criollo')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='huerta',
            name='frutaHuerta',
            field=models.CharField(choices=[('', '(Seleccione)'), ('AGT', 'Aguacate'), ('LMN', 'Limon')], default='AGT', max_length=3),
        ),
        migrations.AlterField(
            model_name='huerta',
            name='ubicacionHuerta',
            field=models.CharField(choices=[('', '(Seleccione)'), ('UPN', 'Uruapan'), ('SES', 'Salvador Escalante'), ('TAN', 'Tancítaro'), ('PER', 'Peribán'), ('TCM', 'Tacámbaro'), ('ADR', 'Ario de Rosales')], default='UPN', max_length=3),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='destinoPedido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='OrdenCalibreCalidad',
        ),
    ]
