# Generated by Django 4.1 on 2023-05-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0008_precioautorizado_alter_reportecorte_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frutahuerta',
            name='idHuerta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.huerta'),
        ),
    ]
