# Generated by Django 4.1 on 2023-05-25 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0009_alter_frutahuerta_idhuerta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencorte',
            old_name='tipoHuerta',
            new_name='tipoFruta',
        ),
    ]
