# Generated by Django 4.1 on 2023-05-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0010_rename_tipohuerta_ordencorte_tipofruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportecorte',
            name='idCuadrilla',
        ),
    ]
