# Generated by Django 4.1 on 2023-05-26 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0011_remove_reportecorte_idcuadrilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecorte',
            name='idViaje',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.viajecorte'),
        ),
    ]
