# Generated by Django 4.1 on 2023-05-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0012_alter_reportecorte_idviaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecorte',
            name='cajasCortadas',
            field=models.IntegerField(blank=True),
        ),
    ]
