# Generated by Django 4.1 on 2023-05-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomunnity', '0013_alter_reportecorte_cajascortadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencorte',
            name='frutaHuerta',
        ),
        migrations.RemoveField(
            model_name='ordencorte',
            name='tipoFruta',
        ),
        migrations.RemoveField(
            model_name='viajecorte',
            name='idHuerta',
        ),
        migrations.AddField(
            model_name='ordencorte',
            name='idHuerta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agronomunnity.huerta'),
        ),
        migrations.AlterField(
            model_name='ordencorte',
            name='tipoCorte',
            field=models.CharField(choices=[('', '(Seleccione)'), ('AVN', 'Aventajado'), ('FLC', 'Flor loca')], default='', max_length=3),
        ),
    ]
